# Generated by Django 5.0.4 on 2024-04-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('association', models.CharField(max_length=100)),
                ('arme', models.CharField(blank=True, max_length=100, null=True)),
                ('histoire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
