# Generated by Django 5.0.4 on 2024-04-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='civilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dieu',
            name='civilisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dieux.civilisation'),
        ),
    ]
